name: Build and Deploy Django Project

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3" # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create ZIP file for deployment
        run: |
          zip -r deploy-package.zip . -x "*.git*"

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: deploy-package.zip

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3" # Specify the Python version you are using

      - name: Check for AWS CLI and install if not present
        run: |
          if ! command -v aws &> /dev/null
          then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

      - name: Check for EB CLI and install if not present
        run: |
          if ! command -v eb &> /dev/null
          then
            pip install awsebcli
          fi

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p python-3.12 pawfectmatch --region us-east-1  # Change 'pawfectmatch' to your Elastic Beanstalk application name and region
          eb deploy --staged

      - name: Clean up
        run: |
          sudo rm -rf awscliv2.zip aws
          pip uninstall -r requirements.txt -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          rm deploy-package.zip
         
